### ISSUE TITLE
挑战live算出了比最佳卡组更高的分数

### ISSUE THREAD

**Issue by Neight99** [xfl03/sekai-calculator#1]
![IMG_1454](https://github.com/xfl03/sekai-calculator/assets/32681608/21cda69a-c6fb-4267-9902-f1e144ca65f7)
![IMG_1453](https://github.com/xfl03/sekai-calculator/assets/32681608/a6f61522-3ece-449e-be42-e8ecc9d8391a)

**Comment by xfl03** [comment]
请再确认一次
![Snipaste_2024-03-15_14-41-56](https://github.com/xfl03/sekai-calculator/assets/3205159/fcb0d3fc-ff3d-448e-a2ce-bda4bba69e09)

**Comment by Neight99** [comment]
现在对了，因为出新卡了
